Use `mktemp` to make temp file in `crlf2l/lf2crlf`

diff --git a/bin/crlf2lf b/bin/crlf2lf
--- a/bin/crlf2lf
+++ b/bin/crlf2lf
@@ -2,8 +2,13 @@
 #
 # Converts `CRLF` (Windows) line endings to `LF` (Unix).
 
-FILES="$@"
-for file in "${FILES}"; do
-  sed "s/$(printf '\r')//" < "${file}" > "/tmp/${file}.crlf.tmp"
-  mv "/tmp/${file}.crlf.tmp" "${file}"
+for file in "$@"; do
+  if [[ -f "${file}" ]] && [[ -r "${file}" ]] && [[ -w "${file}" ]]; then
+    temp_file="$(mktemp)"
+    sed "s/$(printf '\r')//" < "${file}" > "${temp_file}"
+    mv "${temp_file}" "${file}"
+  else
+    echo "Failed to open file: '${file}'" 1>&2
+    exit 1
+  fi
 done
