Edit the output style of install script

diff --git a/bin/dotfiles b/bin/dotfiles
--- a/bin/dotfiles
+++ b/bin/dotfiles
@@ -30,7 +30,7 @@ EOS
 # Usage: install_dotfiles
 #######################################
 install_dotfiles() {
-  e_header '=> Installing...'
+  e_header 'Installing...'
 
   # Executable files
   link_file 'bin/dotfiles' '.local/bin/dotfiles'
@@ -92,7 +92,7 @@ install_dotfiles() {
 # Usage: download_dotfiles
 #######################################
 download_dotfiles() {
-  e_header '=> Downloading...'
+  e_header 'Downloading...'
 
   if command_exists 'git'; then
     # Use Git to clone the remote repository.
@@ -119,7 +119,7 @@ download_dotfiles() {
 # Usage: sync_dotfiles
 #######################################
 sync_dotfiles() {
-  e_header '=> Synchronizing...'
+  e_header 'Synchronizing...'
 
   if ! command_exists 'git'; then
     e_warning 'Git is not installed. Skipped synchronization.'
@@ -211,45 +211,45 @@ command_exists() {
 }
 
 #######################################
-# Exits this script with a failure
-# message and returns an exit code.
-# Usage: die MESSAGE [STATUS]
+# Terminates this script with an error
+# message and returns an exit status.
+# Usage: die MESSAGE [EXIT_STATUS]
 #######################################
 die() {
-  e_failure "Terminated: ${1}" 1>&2
+  printf ' \033[1;31m✘ Terminated: %s\033[0m\n' "${1}" 1>&2
   exit "${2:-1}"
 }
 
 #######################################
 # Prints a header message.
-# Usage: e_header MESSAGE
+# Usage: e_header MESSAGE...
 #######################################
 e_header() {
-  printf '\033[1;37m%s\033[0m\n' "$@"
+  printf '\n\033[1;37m%s\033[0m\n' "$@"
 }
 
 #######################################
 # Prints a success message.
-# Usage: e_success MESSAGE
+# Usage: e_success MESSAGE...
 #######################################
 e_success() {
-  printf '\033[0;32m%s %s\033[0m\n' '✔' "$@"
+  printf ' \033[1;32m✔\033[0m %s\n' "$@"
 }
 
 #######################################
-# Prints a failure message.
-# Usage: e_failure MESSAGE
+# Prints a error message.
+# Usage: e_error MESSAGE...
 #######################################
-e_failure() {
-  printf '\033[0;31m%s %s\033[0m\n' '✘' "$@"
+e_error() {
+  printf ' \033[1;31m✘\033[0m %s\n' "$@"
 }
 
 #######################################
 # Prints a warning message.
-# Usage: e_warning MESSAGE
+# Usage: e_warning MESSAGE...
 #######################################
 e_warning() {
-  printf '\033[0;33m%s %s\033[0m\n' '!' "$@"
+  printf ' \033[1;33m!\033[0m %s\n' "$@"
 }
 
 #######################################
@@ -279,8 +279,8 @@ main() {
   # Install dotfiles.
   install_dotfiles
 
-  echo 'Completed.'
-  echo 'Restart the shell before you continue.'
+  e_header 'Completed.'
+  e_warning 'Restart the shell before you continue.'
 }
 
 main "$@"
